[package]
name = "mdbook"
version = "0.1.0"
authors = ["Mathieu David <mathieudavid@mathieudavid.org>"]
description = "create books from markdown files (like Gitbook)"
documentation = "http://azerupi.github.io/mdBook/index.html"
repository = "https://github.com/azerupi/mdBook"
keywords = ["book", "gitbook", "rustbook", "markdown"]
license = "MPL-2.0"
readme = "README.md"
build = "build.rs"
exclude = [
    "book-example/*",
    "src/theme/stylus",
]

[dependencies]
clap = "2.1.2"
toml = "0.1.27"
handlebars = "0.14.0"
rustc-serialize = "0.3.16"
pulldown-cmark = "0.0.6"

# Watch feature
notify = { version = "2.5.4", optional = true }
time = { version = "0.1.33", optional = true }
crossbeam = { version = "0.2.8", optional = true }


# Tests
[dev-dependencies]
tempdir = "0.3.4"


[features]
default = ["output", "watch"]
debug = []
output = []
regenerate-css = []
watch = ["notify", "time", "crossbeam"]

[[bin]]
doc = false
name = "mdbook"
path = "src/bin/mdbook.rs"
