[package]
name = "mdbook"
version = "0.2.4-alpha.0"
authors = [
    "Mathieu David <mathieudavid@mathieudavid.org>",
    "Michael-F-Bryan <michaelfbryan@gmail.com>",
    "Matt Ickstadt <mattico8@gmail.com>"
]
documentation = "http://rust-lang-nursery.github.io/mdBook/index.html"
edition = "2018"
exclude = ["/book-example/*"]
keywords = ["book", "gitbook", "rustbook", "markdown"]
license = "MPL-2.0"
readme = "README.md"
repository = "https://github.com/rust-lang-nursery/mdBook"
description = "Creates a book from markdown files"

[dependencies]
clap = "2.24"
chrono = "0.4"
handlebars = { version = "1.0", default-features = false, features = ["no_dir_source"] }
serde = "1.0"
serde_derive = "1.0"
error-chain = "0.12"
serde_json = "1.0"
pulldown-cmark = "0.1.2"
lazy_static = "1.0"
log = "0.4"
env_logger = "0.5"
toml = "0.4.8"
memchr = "2.0"
open = "1.1"
regex = "1.0.0"
tempfile = "3.0"
itertools = "0.7"
shlex = "0.1"
toml-query = "0.7"

# Watch feature
notify = { version = "4.0", optional = true }

# Serve feature
iron = { version = "0.6", optional = true }
staticfile = { version = "0.5", optional = true }
ws = { version = "0.7", optional = true}

# Search feature
elasticlunr-rs = { version = "2.3", optional = true, default-features = false }
ammonia = { version = "2.1", optional = true }

[dev-dependencies]
select = "0.4"
pretty_assertions = "0.5"
walkdir = "2.0"
# FIXME(issue #898)
pulldown-cmark-to-cmark = "=1.1.0"

[features]
default = ["output", "watch", "serve", "search"]
debug = []
output = []
watch = ["notify"]
serve = ["iron", "staticfile", "ws"]
search = ["elasticlunr-rs", "ammonia"]

[[bin]]
doc = false
name = "mdbook"
