[package]
name = "mdbook"
version = "0.0.16"
authors = ["Mathieu David <mathieudavid@mathieudavid.org>"]
description = "create books from markdown files (like Gitbook)"
documentation = "http://azerupi.github.io/mdBook/index.html"
repository = "https://github.com/azerupi/mdBook"
keywords = ["book", "gitbook", "rustbook", "markdown"]
license = "MPL-2.0"
readme = "README.md"
build = "build.rs"
include = ["data"]
exclude = [
    "book-example/*",
    "data/assets/_html-template/_stylus",
]


[dependencies]
clap = "2.19.2"
handlebars = { version = "0.23.0", features = ["serde_type"] }
serde = "0.8"
serde_derive = "0.8"
serde_json = "0.8"
pulldown-cmark = "0.0.8"
regex = "0.1"
glob = "0.2"
log = "0.3"
env_logger = "0.3"
toml = { version = "0.2", features = ["serde"] }
open = "1.1"
phf = "0.7"
includedir = "0.2"

# Watch feature
notify = { version = "3.0", optional = true }
time = { version = "0.1.34", optional = true }
crossbeam = { version = "0.2.8", optional = true }

# Serve feature
iron = { version = "0.4", optional = true }
staticfile = { version = "0.3", optional = true }
ws = { version = "0.5.1", optional = true}

[build-dependencies]
includedir_codegen = "0.2"

# Tests
[dev-dependencies]
tempdir = "0.3.4"

[features]
default = ["output", "watch", "serve"]
debug = []
output = []
regenerate-css = []
watch = ["notify", "time", "crossbeam"]
serve = ["iron", "staticfile", "ws"]

[[bin]]
doc = false
name = "mdbook"
path = "src/bin/mdbook.rs"
