[package]
name = "mdbook"
version = "0.0.4"
authors = ["Mathieu David <mathieudavid@mathieudavid.org>"]
description = "create books from markdown files (like Gitbook)"
documentation = "http://azerupi.github.io/mdBook/index.html"
repository = "https://github.com/azerupi/mdBook"
keywords = ["book", "gitbook", "rustbook", "markdown"]
license = "MPL-2.0"
readme = "README.md"
build = "build.rs"
exclude = [
    "book-example/*",
    "src/theme/stylus",
]

[dependencies]
clap = "~1.5.3"
handlebars = "~0.12.0"
rustc-serialize = "~0.3.16"
pulldown-cmark = "~0.0.3"

[build-dependencies]
sass-rs = "0.0.18"


# Watch feature
[dependencies.notify]
version = "^2.4.1"
optional = true

[dependencies.time]
version = "^0.1.33"
optional = true

[dependencies.crossbeam]
version = "^0.2.0"
optional = true

# Tests
[dev-dependencies]
tempdir = "~0.3.4"


[features]
default = ["output", "watch"]
debug = []
output = []
regenerate-css = []
watch = ["notify", "time", "crossbeam"]

[[bin]]
doc = false
name = "mdbook"
path = "src/bin/mdbook.rs"
