[package]
name = "mdbook-wordcount"
version = "0.1.0"
authors = ["Michael Bryan <michaelfbryan@gmail.com>"]
workspace = "../../../.."

[dependencies]
mdbook = { path = "../../../.." }
serde = "1.0"
serde_derive = "1.0"
